### ISSUE TITLE
Author name in header on post page should be relocated beside post date

### ISSUE THREAD

**Issue by nileane** [Nildeala/Stitch-Blue#11]
and obviously, @blog.title should take its place.

**Comment by gllmhyt** [comment]
Working on it. Results so far.

![capture d ecran de 2017-08-17 11-19-20](https://user-images.githubusercontent.com/696539/29405359-f5f9cece-833d-11e7-945a-29bd96b4807b.png)
![capture d ecran de 2017-08-17 11-19-12](https://user-images.githubusercontent.com/696539/29405360-f6048828-833d-11e7-8f42-75028aadfa8d.png)
