### ISSUE TITLE
Stitch Blue needs a logo

### ISSUE THREAD

**Issue by nileane** [Nildeala/Stitch-Blue#18]
It will be used by default on homepage, in the header and as favicon.

**Comment by nileane** [comment]
![stitch-blue-256](https://cloud.githubusercontent.com/assets/914451/7972783/a534410e-0a4f-11e5-86cf-15397c3d01a6.png)

There we go
Thanks @postblue

**Comment by nileane** [comment]
It was included [this commit](https://github.com/Schoewilliam/Stitch-Blue/commit/492d757572659f37e4de1307ab367c7377ee7ef7)

**Comment by gllmhyt** [comment]
HAHAHA, you did it!
