### ISSUE TITLE
Incomplete Version?

### ISSUE THREAD

**Issue by rakernel** [Nildeala/Stitch-Blue#20]
Is this an incomplete version?
I found it has a lot differences between test and screenshots

Preferring the complete one :)

**Comment by ghost** [comment]
Looks pretty good to me even on a default Ghost installation:

![default_ghost_with_stitch_blue](https://cloud.githubusercontent.com/assets/8741873/8827637/1e66d050-308e-11e5-8b69-ed289ad6c7be.jpg)

My guess is you haven't set a blog cover, neither post covers, or haven't publish enough :laughing:

**Comment by nileane** [comment]
Hi. There might be some differences between the screenshots in the README and the actual look of the theme because it is not actually totally ready, and still prone to be changed.

The screenshot @fabienwang posted is pretty accurate as of now though :)
